"""Backend protocols for Cendry."""

import datetime
from collections.abc import AsyncIterator, Iterator
from typing import Any, Literal, Protocol

from .backends.types import DocResult, WriteResult


class Backend(Protocol):
    """Sync backend protocol."""

    def get_collection_ref(
        self, collection: str, parent_collection: str | None, parent_id: str | None
    ) -> Any: ...
    def get_doc_ref(self, col_ref: Any, doc_id: str | None) -> Any: ...
    def doc_ref_id(self, doc_ref: Any) -> str: ...
    def get_doc(self, doc_ref: Any, *, transaction: Any | None = None) -> DocResult: ...
    def get_all(
        self, doc_refs: list[Any], *, transaction: Any | None = None
    ) -> Iterator[DocResult]: ...
    def set_doc(
        self, doc_ref: Any, data: dict[str, Any], *, writer: Any | None = None
    ) -> WriteResult: ...
    def create_doc(
        self, doc_ref: Any, data: dict[str, Any], *, writer: Any | None = None
    ) -> WriteResult: ...
    def update_doc(
        self,
        doc_ref: Any,
        updates: dict[str, Any],
        *,
        writer: Any | None = None,
        precondition: Any | None = None,
    ) -> WriteResult: ...
    def delete_doc(
        self,
        doc_ref: Any,
        *,
        writer: Any | None = None,
        precondition: Any | None = None,
    ) -> None: ...
    def query(self, col_ref: Any) -> Any: ...
    def query_group(self, collection: str) -> Any: ...
    def apply_filter(self, query: Any, field: str, op: str, value: Any) -> Any: ...
    def apply_composite(self, query: Any, op: str, filters: list[Any]) -> Any: ...
    def apply_order(self, query: Any, field: str, direction: str) -> Any: ...
    def apply_limit(self, query: Any, n: int) -> Any: ...
    def apply_cursor(
        self,
        query: Any,
        cursor_type: Literal["start_at", "start_after", "end_at", "end_before"],
        value: Any,
    ) -> Any: ...
    def stream(self, query: Any) -> Iterator[DocResult]: ...
    def select_fields(self, query: Any, fields: list[str]) -> Any: ...
    def count(self, query: Any) -> int: ...
    def new_batch(self) -> Any: ...
    def new_transaction(self, max_attempts: int, read_only: bool) -> Any: ...
    def commit_batch(self, batch: Any) -> None: ...
    def on_doc_snapshot(self, doc_ref: Any, callback: Any) -> Any: ...
    def on_query_snapshot(self, query: Any, callback: Any) -> Any: ...
    def make_precondition(self, update_time: datetime.datetime) -> Any: ...
    def close(self) -> None: ...


class AsyncBackend(Protocol):
    """Async backend protocol."""

    def get_collection_ref(
        self, collection: str, parent_collection: str | None, parent_id: str | None
    ) -> Any: ...
    def get_doc_ref(self, col_ref: Any, doc_id: str | None) -> Any: ...
    def doc_ref_id(self, doc_ref: Any) -> str: ...
    async def get_doc(self, doc_ref: Any, *, transaction: Any | None = None) -> DocResult: ...
    async def get_all(
        self, doc_refs: list[Any], *, transaction: Any | None = None
    ) -> AsyncIterator[DocResult]: ...
    async def set_doc(
        self, doc_ref: Any, data: dict[str, Any], *, writer: Any | None = None
    ) -> WriteResult: ...
    async def create_doc(
        self, doc_ref: Any, data: dict[str, Any], *, writer: Any | None = None
    ) -> WriteResult: ...
    async def update_doc(
        self,
        doc_ref: Any,
        updates: dict[str, Any],
        *,
        writer: Any | None = None,
        precondition: Any | None = None,
    ) -> WriteResult: ...
    async def delete_doc(
        self,
        doc_ref: Any,
        *,
        writer: Any | None = None,
        precondition: Any | None = None,
    ) -> None: ...
    def query(self, col_ref: Any) -> Any: ...
    def query_group(self, collection: str) -> Any: ...
    def apply_filter(self, query: Any, field: str, op: str, value: Any) -> Any: ...
    def apply_composite(self, query: Any, op: str, filters: list[Any]) -> Any: ...
    def apply_order(self, query: Any, field: str, direction: str) -> Any: ...
    def apply_limit(self, query: Any, n: int) -> Any: ...
    def apply_cursor(
        self,
        query: Any,
        cursor_type: Literal["start_at", "start_after", "end_at", "end_before"],
        value: Any,
    ) -> Any: ...
    async def stream(self, query: Any) -> AsyncIterator[DocResult]: ...
    def select_fields(self, query: Any, fields: list[str]) -> Any: ...
    async def count(self, query: Any) -> int: ...
    def new_batch(self) -> Any: ...
    def new_transaction(self, max_attempts: int, read_only: bool) -> Any: ...
    async def commit_batch(self, batch: Any) -> None: ...
    def on_doc_snapshot(self, doc_ref: Any, callback: Any) -> Any: ...
    def on_query_snapshot(self, query: Any, callback: Any) -> Any: ...
    def make_precondition(self, update_time: datetime.datetime) -> Any: ...
    async def close(self) -> None: ...
